node {

    stage('Initialize') {
        cleanWs()

        def gitUrl = scm.getUserRemoteConfigs()[0].getUrl()
        def credentialsId = scm.getUserRemoteConfigs()[0].getCredentialsId()

        parameters {
            gitParameter name: 'TAG', type: 'PT_TAG', defaultValue: 'origin/master'
            gitParameter branchFilter: 'origin/master', defaultValue: 'master', name: 'BRANCH', type: 'PT_BRANCH'
        }

        checkout([$class                           : 'GitSCM',
                  branches                         : [[name: "${params.TAG}"]],
                  doGenerateSubmoduleConfigurations: false,
                  extensions                       : [],
                  gitTool                          : 'Default',
                  submoduleCfg                     : [],
                  userRemoteConfigs                : [[credentialsId: credentialsId, branch: "${params.BRANCH}", url: gitUrl]]
        ])

        env.ecr = "393305049144.dkr.ecr.eu-central-1.amazonaws.com/digitoll-services-erp"

        def matcher = readFile('pom.xml') =~ '<version>(.+?)</version>'
        env.version = matcher ? matcher[0][1] : null
    }

    stage ("Run tests") {
        sh 'mvn clean test -am -pl erp'
    }

    stage('Build') {
        def applicationProperties = "erp/src/main/resources/application.properties"
        def gitLatestCommit = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()

        sh "cp $applicationProperties.$ENV $applicationProperties"
        sh 'cp erp/src/main/resources/bootstrap.yml.$ENV erp/src/main/resources/bootstrap.yml'
        sh 'cp erp/Dockerfile.$ENV erp/Dockerfile'

        sh """echo -e "\\ninfo.build.number=$BUILD_NUMBER" >> $applicationProperties"""
        sh """echo "info.application.version=${version}" >> $applicationProperties"""
        sh """echo "info.git.commit=$gitLatestCommit" >> $applicationProperties"""

        sh "mvn clean package -Dmaven.test.skip=true"
    }

    stage('Build image') {
        sh "docker build -t $ecr:${version}.$BUILD_NUMBER -t $ecr:$ENV erp"
    }

//for tests Jenkins
//should be uncommented later
//     stage('Push to ECR') {
//         sh '$(aws ecr get-login --no-include-email)'
//         sh "docker push $ecr:${version}.$BUILD_NUMBER"
//         sh "docker push $ecr:$ENV"
//     }
//should be uncommented later
//for tests Jenkins


    stage('Docker clean') {
        sh 'docker images $ecr -q | uniq | xargs -r docker rmi -f'
    }

    //for tests Jenkins - begin to be removed
        if (currentBuild.result == 'SUCCESS') {
            stage('current Build result = success'){
                echo ('current Build result = success, build number = $BUILD_NUMBER')
            }
        }
        else {
            stage('current Build result is not success') {
                steps {
                    echo ("I sniffed ${thisjob.getParent().getItems()}!")
                    echo ("current Build result is not success, build number = $BUILD_NUMBER, ${currentBuild.result}")
                }
            }
        }
    //for tests Jenkins - end of to be removed

//for tests Jenkins
//should be uncommented later: begin
//     stage('Deploy to ECS') {
//         sh 'aws ecs update-service --force-new-deployment --cluster $ENV --service digitoll-services-erp-$ENV'
//     }
//should be uncommented later: end
//for tests Jenkins

//     if($ENV == 'dev') {
//         stage('Build version check') {
//             try {
//                 timeout(5) {
//                     waitUntil {
//                         script {
//                             def r = sh script: """#!/bin/bash
//                                     [ \$(curl -s 'https://erp.dev.digitoll.bg/actuator/info' | jq -r "" | grep -o '$ecr:${version}\\|$BUILD_NUMBER' | wc -l) -eq 2 ] || exit 1
//                             """, returnStatus: true
//                             return (r == 0)
//                         }
//                     }
//                 }
//             } catch ( Exception e ) {
//                 error("Service is down. Aborting")
//             }
//         }
//     }
}