package com.digitoll.commons.model;

import com.digitoll.commons.dto.PosDTO;
import com.digitoll.commons.util.BasicUtils;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Objects;

@Document(collection = "pos")
@ApiModel(description = "Point of sell (POS) which sells vignettes")
public class Pos {

    @Id
    @ApiModelProperty(notes = "Autogenerated ID ", example="5d5182dd0fa97000017ceb70")
    private String id;
    @ApiModelProperty(notes = "Partner ID. " +
            "Please refer to the  partner endpoints", example="5d404dce8b9a8e4011d2f03e")
    private String partnerId;
    private String posIdInPartnersDb;
    //if this exists
    private String kapschPosId;
    @ApiModelProperty(notes = "Name of the POS", example="София, кв. Горублене, ул. Самоковско шосе **, магазин ”****”")
    private String name;
    @ApiModelProperty(notes = "Code used for identifying the POS", example="T00013")
    private String code;

    public Pos() {

    }

    public Pos(PosDTO posDTO) {
        BasicUtils.copyNonNullProps(posDTO,this);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPartnerId() {
        return partnerId;
    }

    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPosIdInPartnersDb() {
        return posIdInPartnersDb;
    }

    public void setPosIdInPartnersDb(String posIdInPartnersDb) {
        this.posIdInPartnersDb = posIdInPartnersDb;
    }

    public String getKapschPosId() {
        return kapschPosId;
    }

    public void setKapschPosId(String kapschPosId) {
        this.kapschPosId = kapschPosId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Pos pos = (Pos) o;
        return Objects.equals(id, pos.id) &&
                Objects.equals(partnerId, pos.partnerId) &&
                Objects.equals(posIdInPartnersDb, pos.posIdInPartnersDb) &&
                Objects.equals(kapschPosId, pos.kapschPosId) &&
                Objects.equals(name, pos.name) &&
                Objects.equals(code, pos.code);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, partnerId, posIdInPartnersDb, kapschPosId, name, code);
    }
}
