package com.digitoll.commons.model;

import io.swagger.annotations.ApiModelProperty;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.DBRef;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;
import java.util.List;

public interface UserProperties {
    @ApiModelProperty(notes = "Autogenerated", example="5d3f11258b9a8e7a66628771")
    String getId();

    @ApiModelProperty(notes = "username used for login", example="john_doe@mail.bg")
    String getUsername();

    @ApiModelProperty(notes = "First name of the user", example="John")
    String getFirstName();

    @ApiModelProperty(notes = "Last name of the user", example="Doe")
    String getLastName();

    @ApiModelProperty(notes = "ID of the partner that the user represents", example="5d404dce8b9a8e4011d2f04e")
    String getPartnerId();

    @ApiModelProperty(dataType = "List",
            example = "[5d5182dd0fa97000017ceb6f]")
    List<String> getPosIds();

//    List<Role> getRoles();

    @ApiModelProperty(notes = "Registration date of the user")
    Date getCreatedAt();

    @ApiModelProperty(notes = "The last time the user has been updated")
    Date getUpdatedAt();

    @ApiModelProperty(notes = "User's active status")
    boolean isActive();

    void setId(String id);

    void setUsername(String username);

    void setFirstName(String firstName);

    void setLastName(String lastName);

    void setPartnerId(String partnerId);

    void setPosIds(List<String> posIds);


//    void setRoles(List<Role> roles);

    void setCreatedAt(Date createdAt);

    void setUpdatedAt(Date updatedAt);

    void setActive(boolean active);

}
