package com.digitoll.commons.kapsch.classes;

import com.digitoll.commons.enumeration.EmissionClass;
import com.digitoll.commons.enumeration.VehicleType;
import com.digitoll.commons.enumeration.VignetteValidityType;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import io.swagger.annotations.ApiModelProperty;
import org.springframework.data.annotation.Id;

import java.util.Objects;

public class EVignetteProduct {


    @Id
    @ApiModelProperty(notes = "Autogenerated ID", example="5d419c15f0f4303dbe2e0aae")
    private String mongoId;

    @ApiModelProperty(notes = "Kapsch Product (Vignette) ID", example="401")
    private Integer id;
    
    @NotBlank
    @ApiModelProperty(notes = "Vehicle type that the vignette is for")
    private VehicleType vehicleType;
    
    @NotBlank
    @ApiModelProperty(notes = "THe emission class according to the euro standards")
    private EmissionClass emissionClass;
    
    @NotNull
    @ApiModelProperty(notes = "The vignette validity duration type")
    private VignetteValidityType validityType;

    @NotNull
    @ApiModelProperty(notes = "The vignette full description")
    private String description;

	public VignetteValidityType getValidityType() {
		return validityType;
	}

	public void setValidityType(VignetteValidityType validityType) {
		this.validityType = validityType;
	}

    public VehicleType getVehicleType() {
        return vehicleType;
    }

    public void setVehicleType(VehicleType vehicleType) {
        this.vehicleType = vehicleType;
    }

    public EmissionClass getEmissionClass() {
        return emissionClass;
    }

    public void setEmissionClass(EmissionClass emissionClass) {
        this.emissionClass = emissionClass;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setMongoId(String mongoId) {
        this.mongoId = mongoId;
    }

    public String getMongoId() {
        return mongoId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        EVignetteProduct product = (EVignetteProduct) o;
        return Objects.equals(mongoId, product.mongoId) &&
                Objects.equals(id, product.id) &&
                vehicleType == product.vehicleType &&
                emissionClass == product.emissionClass &&
                validityType == product.validityType;
    }

    @Override
    public int hashCode() {
        return Objects.hash(mongoId, id, vehicleType, emissionClass, validityType);
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}